### ISSUE TITLE
global selector

### ISSUE THREAD

**Issue by rimmesbe** [bahobab/teacozy#2]
Later in the course we will learn about reset.css and normalize.css files that will take care of reseting these default stylings. The issue with the global selector is it's a little bit overkill as a selector. It processing speed is also slower, that's why you will rarely seen it use on its own.

https://github.com/bahobab/teacozy/blob/master/resources/css/style.css#L1-L5

**Comment by bahobab** [comment]
Great. Understood. Thanks
